/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vip_frendy_opencv_OpenCVManager */

#ifndef _Included_vip_frendy_opencv_OpenCVManager
#define _Included_vip_frendy_opencv_OpenCVManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vip_frendy_opencv_OpenCVManager
 */
JNIEXPORT jobject JNICALL Java_vip_frendy_opencv_OpenCVManager_toBW
  (JNIEnv *, jobject, jobject);

JNIEXPORT jobject JNICALL Java_vip_frendy_opencv_OpenCVManager_toBokeh
        (JNIEnv *, jobject, jobject, jint x, jint y, jint w, jint h, jint blurSize, jint type);

JNIEXPORT jobject JNICALL Java_vip_frendy_opencv_OpenCVManager_toBokehWithCircle
        (JNIEnv *, jobject, jobject, jint r, jint blurSize, jint type);

JNIEXPORT jintArray JNICALL Java_vip_frendy_opencv_OpenCVManager_toEnlarge
        (JNIEnv *, jobject, jintArray, jint, jint, jint, jint, jint, jfloat);

JNIEXPORT jobject JNICALL Java_vip_frendy_opencv_OpenCVManager_toStretch
        (JNIEnv *, jobject, jobject);

JNIEXPORT jobject JNICALL Java_vip_frendy_opencv_OpenCVManager_toCylinder
        (JNIEnv *, jobject, jobject);

JNIEXPORT jint JNICALL Java_vip_frendy_opencv_OpenCVManager_classifier
        (JNIEnv *, jobject, jobject, jstring);

JNIEXPORT jint JNICALL Java_vip_frendy_opencv_OpenCVManager_getFingerCount
        (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
